[package]
name = "mm_file_formats"
version = "0.1.0"
edition = "2021"
description = "Parsers for Magic & Mayhem file formats"

[dependencies]
nom = "7.1.3"
image = "0.24.6"
mm_compression.path = "../mm_compression"