[package]
name = "mm_compression"
version = "0.1.0"
edition = "2021"
description = "Utilities for handling file compression and obfuscation from Magic & Mayhem"

[dependencies]
bitstream-io = "1.6.0"
