[package]
name = "mm_map_rendering"
version = "0.1.0"
edition = "2021"
description = "Rendering of Magic & Mayhem maps"

[dependencies]
image = "0.23.1"
nalgebra = "0.19"
mm_file_formats.path = "../mm_file_formats"
mm_compression.path = "../mm_compression"
